### ISSUE TITLE
Add files directly and not only the links to them

### ISSUE THREAD

**Issue by zuphilip** [UB-Mannheim/zotero-ocr#12]

**Comment by zuphilip** [comment]
Try to replace `linkFromFile` by `importFromFile` should do the trick...

**Comment by zuphilip** [comment]
But this will create a new folder with this attachment and therefore doubling the space usage unnecessary.

**Comment by aborel** [comment]
0.8.1 makes it user-selectable, is it OK to close the issue?

**Comment by aborel** [comment]
Closing.
