### ISSUE TITLE
More flexibility with pdftoppm dependency

### ISSUE THREAD

**Issue by zuphilip** [UB-Mannheim/zotero-ocr#14]
Today, I installed the plugin on a macOS and there was the problem that the `pdftoppm` was not found initially. Then, the easiest was to install it with `brew install poppler` which installed thereby a lot of other things as well. However, that was still not fine then, because the plugin expected the program to lie in the Zotero directory, which could then finally solved by copy and paste.

How can we make this process easier for macOS?

It would be possible to look for other locations of pdftoppm similar to what we already do for tesseract. Is there also an easier installation method for the poppler tools? For windows it was enough to download one file and move it to the correct directory.

**Comment by p3palazzo** [comment]
On Linux, using a symlink rather than copying works, too. I support the request to have an option to specify the path to pdftoppm.

**Comment by prc1212** [comment]
I'm having an issue with this. I've installed Tesseract, Poppler, and Zotero-OCR without a problem. However, I'm not clear on what exactly needs to be copied and pasted into the directory Zotero.app/Contents/MacOS/.

**Comment by zuphilip** [comment]
@prc1212 The executable script  `pdftoppm` should be copied in the same directory as the Zotero executable itself.

**Comment by llity** [comment]
@zuphilip where can I find pdftoppm? there just pdftoppm.cc file.

**Comment by llity** [comment]
@prc1212 Do you solve this issue?

**Comment by zuphilip** [comment]
Such an option is now added in the version 0.4.0.
