### ISSUE TITLE
'Overwrite the initial PDF' duplicates Zotero pdf record

### ISSUE THREAD

**Issue by prc1212** [UB-Mannheim/zotero-ocr#15]
When running z-ocr with the options shown below, a single pdf is generated but the record in Zotero is duplicated.

<img width="651" alt="Screenshot 2020-05-18 at 18 20 22" src="https://user-images.githubusercontent.com/64705985/82236351-44cf3200-9934-11ea-8fe8-ff84088af5e3.png">

I'm using ZotFile, as you can see from the filepaths.

The links aren't broken. Both records refer to the same pdf.

It's easy enough to fix manually, of course, but a bit messy.

**Comment by zuphilip** [comment]
Fixed and part of the newest version 0.4.0. Thank you @prc1212 for reporting.
