### ISSUE TITLE
Nothing happens (Linux)

### ISSUE THREAD

**Issue by asanormie** [UB-Mannheim/zotero-ocr#20]
I have pdftoppm and tesseract in appropriate directories but get no output when I right click > OCR selected pdf. I'm on arch linux but I'm pretty new to the distro. Cannot find any solution that works in the previously solved issues. Thanks!

**Comment by zuphilip** [comment]
@asanormie Can you give some more details? If you click on OCR selected PDF what do you see then afterwards in the "Report error..." window? Moreover, if you click on right click on the file in Zotero and choose "Show file" what other files do you see in this folder?

**Comment by asanormie** [comment]
Thanks for replying! Here is Report Error output: https://pastebin.com/raw/NhmASDPd

Here is the output from ls in the folder "show file" takes me to:

 image-list.txt  'Sibley et al_2018_Addressing Incomplete Psychiatric Histories in Adult ADHD.info.txt'
 page-1.png      'Sibley et al_2018_Addressing Incomplete Psychiatric Histories in Adult ADHD.pdf'
 page-2.png

**Comment by dalito** [comment]
Have you specified the full path including the name of the executable? I had a similar result on Windows when I specified only the path to where tesseract.exe lies without including "tesseract.exe".

**Comment by zuphilip** [comment]
The executable seems to be found here, but the tesseract run lead to the exit code 1.

Can you try to simulate the tesseract call directly? I.e. something like
```
/usr/bin/tesseract /home/hal/Zotero/storage/BPQC2BUE/page-1.png out
```
in your case? Do you see more details about the error then?

**Comment by asanormie** [comment]
Here is the output I get:
`Error opening data file /usr/share/tessdata/eng.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory.
Failed loading language 'eng'
Tesseract couldn't load any languages!
Could not initialize tesseract.`

**Comment by asanormie** [comment]
OK so I made some progress by copying `eng.traineddata` from `/var/lib/flatpak/app/org.gnome.OCRFeeder/current/a74dc418e3c47a73569e385be7219dcccf0ca829e754f4e65aa29e3919dd50ff/files/share/tesseract/tessdata` to `/usr/share/tessdata` 

I now get a complete ocr.txt of the pdf but when I try to open the ocr.pdf it says its broken, and still no feedback from zotero that OCR was successful.

**Comment by asanormie** [comment]
Nevermind, ocr.pdf is no longer broken. Everything appears to be working as it should now, except for affirmative output from Zotero - going to mark this as closed. Thanks for your help!! Awesome program!
