### ISSUE TITLE
Make resolution of extracted images configurable

### ISSUE THREAD

**Issue by serovar** [UB-Mannheim/zotero-ocr#23]
It would be really appreciated, if possible, the addition of a setting to raise the default image quality of the produced OCRed pdf, since the default quality is suboptimal in many instances.

E.g. (Top: Original, Bottom: OCRed version)

![Zotero-OCR](https://user-images.githubusercontent.com/6732420/105640480-985c2d00-5e7e-11eb-8403-83827b3e65f7.jpg)

**Comment by zuphilip** [comment]
The first step is to extract the pages from the pdf into png images. There is a resolution parameter there which currently is set to 300dpi:

https://github.com/UB-Mannheim/zotero-ocr/blob/822f44298dce422a299ebabdd7c987d67e320b03/chrome/content/zoteroocr.js#L128

It is possible to make this also configurable with a parameter. Then you could try to use e.g. 600 better image quality within the newly created pdf.

**Comment by serovar** [comment]
Yes, it would be perfect :)

**Comment by stweil** [comment]
Related pull request: #41.

**Comment by aborel** [comment]
User settings introduced in version 0.8.1, I'm closing the issue.
