### ISSUE TITLE
Difficulty to OCR with the Zotero Beta (latest) on Mac M1

### ISSUE THREAD

**Issue by skishchampi** [UB-Mannheim/zotero-ocr#26]
I am trying to use the plugin with Zotero Beta (latest version) on an Apple M1.

I have tesseract, and poppler tools configured. But there seems to some issue as I am not able to OCR any file. Here is the error I see when looking at Debug Output. 

(1)(+0000007): NS_ERROR_FAILURE Exception: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIProcess.init] [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIProcess.init]" nsresult: "0x80004005 (NS_ERROR_FAILURE)" location: "JS frame :: chrome://zotero/content/xpcom/utilities_internal.js :: Zotero.Utilities.Internal.exec< :: line 762" data: no] Zotero.Utilities.Internal.exec<@chrome://zotero/content/xpcom/utilities_internal.js:762:5 From previous event: oncommand@chrome://zotero/content/standalone/standalone.xul:1:1

Either I have made some mistake in the configuration or how I setting the path ( though I double checked and the paths seem fine, but may be this is a Beta or an M1 issue?

Appreciate your advice. Thanks in advance.

**Comment by zuphilip** [comment]
I can confirm that the plugin works with the latest Zotero Beta as I am using that as well, but I am testing on Windows.

@skishchampi  Can you specify further the configuration for the plugin you are using?

Moreover, try activate the debug output and then do the steps in the plugin again. There you should see the exact commands with paths which are used and whether there might be some misconfiguration there. Maybe copy any relevant lines from the plugin here and then I can try to look further.

**Comment by skishchampi** [comment]
ok, I tried as advised (I think) and here is the output 

> (1)(+0000004): NS_ERROR_FAILURE Exception: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIProcess.init] [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIProcess.init]" nsresult: "0x80004005 (NS_ERROR_FAILURE)" location: "JS frame :: chrome://zotero/content/xpcom/utilities_internal.js :: Zotero.Utilities.Internal.exec< :: line 762" data: no] Zotero.Utilities.Internal.exec<@chrome://zotero/content/xpcom/utilities_internal.js:762:5 From previous event: oncommand@chrome://zotero/content/standalone/standalone.xul:1:1

Sharing the configuration in the screenshot

<img width="633" alt="Screenshot 2021-04-14 at 12 42 53 PM" src="https://user-images.githubusercontent.com/996985/114669171-398cae00-9d1f-11eb-9fd0-e967d8333a61.png">

**Comment by jbenton** [comment]
Just wanted to say I'm running into the same problem on my M1 Mac. Here's my error:

(1)(+0000005): NS_ERROR_FAILURE Exception: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIProcess.init] [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIProcess.init]" nsresult: "0x80004005 (NS_ERROR_FAILURE)" location: "JS frame :: chrome://zotero/content/xpcom/utilities_internal.js :: Zotero.Utilities.Internal.exec< :: line 762" data: no] Zotero.Utilities.Internal.exec<@chrome://zotero/content/xpcom/utilities_internal.js:762:5 From previous event: oncommand@chrome://zotero/content/standalone/standalone.xul:1:1

**Comment by sgroth** [comment]
Same here (Mac OS 11.2.3, Zotero 5.0.97-beta.27+861d5787d):

> (1)(+0000002): NS_ERROR_FAILURE Exception: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIProcess.init] [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIProcess.init]" nsresult: "0x80004005 (NS_ERROR_FAILURE)" location: "JS frame :: chrome://zotero/content/xpcom/utilities_internal.js :: Zotero.Utilities.Internal.exec< :: line 762" data: no] Zotero.Utilities.Internal.exec<@chrome://zotero/content/xpcom/utilities_internal.js:762:5 From previous event: oncommand@chrome://zotero/content/standalone/standalone.xul:1:1

**Comment by zuphilip** [comment]
Sorry for the delay!

@skishchampi You only have indicated the path, but not the actual files.

@jbenton @sgroth Try something like `/opt/homebrew/Cellar/tesseract/4.1.1/bin/tesseract`. Here is an example:

![](https://user-images.githubusercontent.com/6734573/120928616-9a17e600-c6e5-11eb-8398-8fa1cc997015.png)
