### ISSUE TITLE
Issue with missing .dll Files

### ISSUE THREAD

**Issue by ReaderGuy42** [UB-Mannheim/zotero-ocr#29]
I'm way out of my depth here, so I'm not sure what to do:

I've followed the  instructions and the Tesseract install was no problem.

I found a StackOverflow tutorial to install the Poppler files.

I've entered the paths to Tesseract and Poppler in the Zotero extension window, but when I try OCR'ing a file in Zotero via right-click I get a series of error messages about missing .dll Files: freetype.dll, libcurl.dll, zlib.dll, openjp2.dll. 

![Screenshot 2021-05-13 233318](https://user-images.githubusercontent.com/71895400/118190775-dee09200-b443-11eb-91ee-521729cdf8a5.png)

It says to reinstall, but I'm not sure what to reinstall.

Any advice?
Thanks!

**Comment by zuphilip** [comment]
Sorry for the dealy @ReaderGuy42. We collected some hints for the installation of the poppler tools in the wiki: https://github.com/UB-Mannheim/zotero-ocr/wiki/Install-pdftoppm but hopefully you could find a solution in the mean time anyways.

**Comment by ReaderGuy42** [comment]
Thanks :)
