### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by trenkert** [UB-Mannheim/zotero-ocr#3]
I installed zotero-ocr via xpi. I was able to set the tesseract path in the preference window and I can select "OCR selected pdf" from the context menu. However, nothing happens. This is the terminal output:

```
Possibly unhandled rejection:

ZoteroPane is not defined

ReferenceError: ZoteroPane is not defined
    Zotero.OCR</this.recognize<@chrome://zoteroocr/content/zoteroocr.js:7:7
From previous event:
    oncommand@chrome://zotero/content/standalone/standalone.xul:1:1
```

**Comment by zuphilip** [comment]
Okay, maybe it is enough to copy these lines https://github.com/zuphilip/zotero-open-citations/blob/master/chrome/content/zoteroopencitations.js#L9-L11 here as well. I will look into this later...

**Comment by stweil** [comment]
It should be fixed now in Git master. We still have to prepare a new release.

**Comment by zuphilip** [comment]
New release 0.2.0 is out now which also fixed some other problems. Therefore I close this now. If the problem still exists for you @trenkert then feel free to open the issue again.
