### ISSUE TITLE
Document to configure linux and mac have moved, suggestion to include them in the repo's docs

### ISSUE THREAD

**Issue by mateMathieu** [UB-Mannheim/zotero-ocr#31]
Hi,

The linux and the mac configuration document have moved.
Can we include a simple screenshot of the right parameters to use for the configuration?

Thanks

**Comment by stweil** [comment]
See pull request #28 which fixes the link.

> Can we include a simple screenshot of the right parameters to use for the configuration?

The right parameters depend on your local environment. Handling all cases requires a lot of screenshots.

**Comment by mateMathieu** [comment]
Just setting the default parameters in the UI would be great also!
