### ISSUE TITLE
tesseract.js with WebAssembly

### ISSUE THREAD

**Issue by fangzhou-xie** [UB-Mannheim/zotero-ocr#32]
Thanks for this package! I just tried out this extension yesterday and found it great.

Just out of curiosity, is it possible to compile the `tesseract` into WebAssembly by using [`tesseract.js`](https://github.com/naptha/tesseract.js) so that the end-user don't need to install the tesseract package on their local machine?

I know little about JS and I am not sure if this is viable. But I am asking because I think the current installation might be a bit troublesome for non-programmer/developer who doesn't know how to install `homebrew`, how to use `apt-get install`, etc. I can see that many people ask questions on Zotero forum regarding the installation and I just wonder how to make it easier.

Thanks again.

**Comment by zuphilip** [comment]
Sorry for the delay @fangzhou-xie . That is a good question but w.r.t. to the possiblities with pure JS libraries I don't know the answer.

At the very beginning I also thought about the different possiblities to implement it: either call the locally installed tools (as it is now) or do everything with Javascript and special libraries as the one you mentioned. Possibly other features as saving to files could be then more challenging to do.

Anyways, I think that changing it to a pure JS plugin would be complete rewrite of the plugin, which I doubt that I will do. If anyone is interested in doing that, then maybe the plugin here could server as some template to start.
