### ISSUE TITLE
keeps running without finishing job

### ISSUE THREAD

**Issue by nickallyn** [UB-Mannheim/zotero-ocr#34]
I have installed Tesseract but when I go to OCR a document the log keeps going for hours but the OCR'd pdf is never produced.

Debug ID D405980180.

**Comment by zuphilip** [comment]
Sorry @nickallyn for the delay. I cannot look at these debug messages. Is the issue still there? Maybe you can on yourself activate the debug logging in Zotero and look if there is anything related mentioned there.

**Comment by borry666** [comment]
Hi, I hava a similar question.
After intalling the plug-in OCR in zotero, I tried "OCR the selected pdf(s)", but zotero even didn't have window to tell me whether it was processing or not. There was nothing move. However the interesting thing is that I could know that the cpu is working, so I'm not sure this will help you guys.

For you imformation, the computer is Mac m1pro chip with Ventura 13.0 and the Zotero is 6.0, installed the OCR in the version of 0.6.0.

Thanks a lot.

**Comment by zuphilip** [comment]
Closing this now, because of inactivity of regarding the initial question. Second questions sounds like #54.
