### ISSUE TITLE
producing scanned pdf from a wrong file

### ISSUE THREAD

**Issue by SYQsb** [UB-Mannheim/zotero-ocr#35]
system is macbook air, M1, Monterey, Zotero 5.0.97-beta.59+abe8c39c5, add-on the latest.

when i choose an attached pdf and click `OCR selected PDF`, after some while it does produce a scanned pdf file, but **not the one i selected**, and no matter which i choose to scan, i always get the same file

**Comment by Nonameentered** [comment]
I get this issue too. @SYQsb did you ever find a solution?

**Comment by SYQsb** [comment]
> I get this issue too. @SYQsb did you ever find a solution?

no I couldn't find the cause. After a few rebooting it came back to normal, without me adjusting anything.
Anyway I have quit using this add-on now...

**Comment by zuphilip** [comment]
Sorry for the delay @SYQsb and @Nonameentered . I am not sure that I understand your problem correctly. Do you have an entry in Zotero with multiple PDFs attached to it and select one of them?
