### ISSUE TITLE
Can't config the path to OCR engine on linux

### ISSUE THREAD

**Issue by morpheus-sapiens-amans** [UB-Mannheim/zotero-ocr#39]
tesseract-ocr is he engine used by Zotero OCR to recognize and extract content, but the installation guide only shows the path for windows machine. 

1. I tried `whereis tessarect-ocr` to locate the path for the engine and I got `/usr/share/tesseract-ocr` as a result, but when I applied to the preferences in Zotero, it says no executable found.

Does anyone knows what to do to config? 

thanks

**Comment by morpheus-sapiens-amans** [comment]
I've just found this other post that shows the same problem as I do.

[zotero forums](https://forums.zotero.org/discussion/90576/ocr-parameters-on-linux)

> Hi, I wanted to check with you guys what are the parameters for the OCR plugin on linux.
I went to the github page and found the link to configuration for mac and linux does not work correctly.
So here are my config param:

> First, I installed tesseract-ocr provided by my repositories.

> For the OCR engine: /usr/bin/tesseract
For pdftoppm: /usr/bon/pdftoppm
For the language script: script/Latin

**Comment by zuphilip** [comment]
Is `/usr/share/tesseract-ocr` not only the directory? Then you should try something like `/usr/share/tesseract-ocr/tesseract` instead. But you can also try to leave it simple empty, then the default options will be tried out:
https://github.com/UB-Mannheim/zotero-ocr/blob/9a1e87c8e5a588c7f9c046f812ee7de55f277ec1/chrome/content/zoteroocr.js#L36

If this does not help, then activate the debug log and look what exactly is tried to call tesseract.

**Comment by stweil** [comment]
`/usr/bin/tesseract` is the correct setting for the typical installation on Linux.

**Comment by Seraphli** [comment]
Hi, I'm having a similar problem. In my case, I have set the right path. But it tells no executable found.
![image](https://user-images.githubusercontent.com/1586755/226874230-495c6cc3-9d0b-464f-a381-af18615613c1.png)
```
~ ❯ which tesseract   
/usr/bin/tesseract
~ ❯ which pdftoppm                  
/usr/bin/pdftoppm
```
I don't know why.

**Comment by ChildishGiant** [comment]
For me it was because I was using the flatpak version which messes everything up. Reinstalling from the tarball as described [here](https://www.zotero.org/support/installation) made everything work.

**Comment by ohickl** [comment]
> Hi, I'm having a similar problem. In my case, I have set the right path. But it tells no executable found. ![image](https://user-images.githubusercontent.com/1586755/226874230-495c6cc3-9d0b-464f-a381-af18615613c1.png)
> 
> ```
> ~ ❯ which tesseract   
> /usr/bin/tesseract
> ~ ❯ which pdftoppm                  
> /usr/bin/pdftoppm
> ```
> 
> I don't know why.

Same problem here on Nobara Linux 38 Wayland (GNOME 44.2).

**Comment by zuphilip** [comment]
Try to activate the debug output in Zotero and then select a test PDF and click on the "OCR selected PDF(s)". Then in the debug output you should see exactly the path used to call the different tools.

**Comment by Seraphli** [comment]
When I tested it today, I found that the issue seemed to be resolved. It's been a long time since then, so I don't know what caused the problem at that time.
