### ISSUE TITLE
Change language to chi_sim_vert, perform OCR didn't response

### ISSUE THREAD

**Issue by YangWaldon** [UB-Mannheim/zotero-ocr#44]
① installed tesseract as well as poppler
② entered the path of two exe's in the zotero ocr plugin 
③ in order to ocr the Chinese pdf, entered chi_sim_vert in the language field
![image](https://user-images.githubusercontent.com/49675185/180158736-33077bcd-a8a8-4ae7-8290-5df2c0a628df.png)

④ Run the plugin, only a black window popped up, but did not produce any running results 
![image](https://user-images.githubusercontent.com/49675185/180158893-2c20278c-b6d4-4804-81c3-0f19801e9703.png)

**Comment by YangWaldon** [comment]
I further found that after pdftoppm converts the pdf (the document is all in Chinese) to many png images (in the same folder as the pdf), it doesn't call tesseract to ocr those images (provided I have the option to save the png turned off. 
![image](https://user-images.githubusercontent.com/49675185/180184559-9c20d796-136f-454d-b579-093ec4c1aee1.png)


Shouldn't tesseract be processing images in tiff format?

I tested it and both pdftoppm and tesseract are working fine in cmd using the command to call and use

**Comment by decdox** [comment]
Cause: 
It seems that the installation tutorial of `Tesseract OCR` listed in `Zotero-ocr` only supports English. One can check the available language support in a `Tesseract` terminal/console by running:
```bash
tesseract --tesseract --list-langs
```
There should be something like this:
```bash
List of available languages in "C:\Program Files\Tesseract-OCR/tessdata/" (2):
eng  # English
osd  # For Orientation and Script Detection
```

My solution: 
1. Download trained model for Chinese (simplified) language at [tessdata repository](https://github.com/tesseract-ocr/tessdata). The file you need is named `chi_sim.traineddata` or `chi_sim_vert.traineddata`, click:
- [Chinese (simplified)](https://github.com/tesseract-ocr/tessdata/blob/main/chi_sim.traineddata)
- [Chinese (simplified,  vertical)](https://github.com/tesseract-ocr/tessdata/blob/main/chi_sim_vert.traineddata)
Other languages can be found at the repo.

2. Install language model
You just need to place the downloaded file in the `tessdata` directory where `Tesseract` looks for language data. Check installation with path like those
- For Linux: /usr/share/tesseract-ocr/4.00/tessdata/
- For Windows: C:\Program Files\Tesseract-OCR\tessdata\

3. Check the language support again with `tesseract --tesseract --list-langs` and there should be something like:
```bash
C:\Program Files\Tesseract-OCR>tesseract --list-langs
List of available languages in "C:\Program Files\Tesseract-OCR/tessdata/" (3):
chi_sim  # Chinese simplified is installed
eng
osd
```

**Comment by zingff** [comment]
For someone may run into the same issue:
**Cause:** 
It seems that the installation tutorial of `Tesseract OCR` listed in `Zotero-ocr` only supports English. One can check the available language support in a `Tesseract` terminal/console by running:
```bash
tesseract --tesseract --list-langs
```
There should be something like this:
```bash
List of available languages in "C:\Program Files\Tesseract-OCR/tessdata/" (2):
eng  # English
osd  # For Orientation and Script Detection
```

**My solution:** 
1. Download trained model for Chinese (simplified) language at [tessdata repository](https://github.com/tesseract-ocr/tessdata). The file you need is named `chi_sim.traineddata` or `chi_sim_vert.traineddata`, click:
- [Chinese (simplified)](https://github.com/tesseract-ocr/tessdata/blob/main/chi_sim.traineddata)
- [Chinese (simplified,  vertical)](https://github.com/tesseract-ocr/tessdata/blob/main/chi_sim_vert.traineddata)
Other languages can be found at the repo.

2. Install language model
You just need to place the downloaded file in the `tessdata` directory where `Tesseract` looks for language data. Check installation with path like those
- For Linux: /usr/share/tesseract-ocr/4.00/tessdata/
- For Windows: C:\Program Files\Tesseract-OCR\tessdata\

3. Check the language support again with `tesseract --tesseract --list-langs` and there should be something like:
```bash
C:\Program Files\Tesseract-OCR>tesseract --list-langs
List of available languages in "C:\Program Files\Tesseract-OCR/tessdata/" (3):
chi_sim  # Chinese simplified is installed
eng
osd
```

**Comment by zuphilip** [comment]
This was probably solved by installing the additional languages in Tesseract. I am closing the issue now. If you still have problems please make sure to update first to version 0.7.0 and then feel free to open a new issue here.
