### ISSUE TITLE
OCR Produces corrupted file

### ISSUE THREAD

**Issue by user20230302** [UB-Mannheim/zotero-ocr#51]
Running the plugin produces a corrupted PDF file that cannot be opened in Zotero nor in other PDF readers. When the settings are set to "overwrite the initial PDF" the process fails after page 5, but with this setting disabled the plugin will complete the process. However, in both cases the output PDF is corrupted. 

Current settings: 
![image](https://user-images.githubusercontent.com/126825686/234081059-1d1deb62-cac3-455f-b4f6-143160db2460.png)

**Comment by user20230302** [comment]
similar to issue #48

**Comment by stweil** [comment]
Pleas continue the discussion at issue #48.
