### ISSUE TITLE
Zotero 7 Support

### ISSUE THREAD

**Issue by 7596ff** [UB-Mannheim/zotero-ocr#52]
Per the [Zotero Forums], all Zotero plugins will need to be rewritten to support the next major version.

[Zotero Forums]: https://forums.zotero.org/discussion/105094/announcing-the-zotero-7-beta

**Comment by ricklei2777** [comment]
I agree! Zotero 7 is great and beautiful

**Comment by stweil** [comment]
Contributions which add the required updates are welcome!

Related documentation:
https://www.zotero.org/support/dev/zotero_7_for_developers

Ideally the plugin should support both Zotero 6 and Zotero 7, at least for some time.

**Comment by lisasuosuo** [comment]
I agree too!

**Comment by aborel** [comment]
I'm trying to port the plugin to Zotero 7.  This is a first for me, so I'm really learning by doing - but I think I'm getting there.

**Comment by aborel** [comment]
I have reached the point where everything seems to work, but it is only for Zotero 7: I am not really interested in learning how to deal with Zotero 6, since it might go away soon-ish... @stweil would a Z7-only PR be acceptable?

**Comment by zuphilip** [comment]
That is great to hear @aborel and I am looking forward for any Zotero 7 compatible version of the plugin. Thank you very much for working on that!

Zotero 6.0.30 is the current version and Zotero 7 is in (stable) Beta. However, I am not sure that they switch soon the main version. But it should be no problem to have two different branches for the two versions. We could do this first also without releasing any new version here. The [build script](https://github.com/UB-Mannheim/zotero-ocr/blob/master/build.sh) can also been run locally until we have a better solution. We need to be careful with releasing because the GitHub release will automatically been updated for all current users of the plugin.

**Comment by aborel** [comment]
@zuphilip I agree that updates are an important concern, and it is probably better to not have an official release at this point. Also, a new branch makes sense. I'm going to clean up my repository, then I'll submit my PR when the new branch is available here.

**Comment by BoseJohnson** [comment]
please somebody update this add-on for z7,

**Comment by kaiwen-wang** [comment]
[Here are some tips](https://www.kaiwenwang.me/writing/20240307_ocr-pdf) for doing it manually that I wrote on my blog. I might be interested in writing a Zotero 7 OCR plugin as it doesn't seem too complicated, but I think `ocrmypdf` has a lot of good add-ins that `tesseract` by itself doesn't have.

**Comment by stweil** [comment]
Here is a test version of the Zotero OCR plugin: https://github.com/UB-Mannheim/zotero-ocr/actions/runs/8417350410/artifacts/1354939817. It should work with Zotero 6 and Zotero 7.

- download the ZIP file
- unzip the file
- install the extracted XPI file
- report any issues which you might notice

**Comment by stweil** [comment]
The new [release 0.7.0](https://github.com/UB-Mannheim/zotero-ocr/releases/tag/0.7.0) now supports Zotero 7 (thanks to @aborel) while still being compatible with Zotero 6, too.

**Comment by stweil** [comment]
Did you install the latest release 0.7.2? There should be the same UI element for starting OCR as in Zotero 6.

**Comment by dstark** [comment]
> Did you install the latest release 0.7.2?

Apparently not. It looks like I was just so excited to see the update for Zotero 7 that I grabbed the 0.7.0 version from the link above, installed it, and didn't check if it was still the most recent version. Sorry about that. 0.7.2 works perfectly and, yes, does have the expected UI element. Thanks so much!
