### ISSUE TITLE
PDF does not auto-link to group libraries

### ISSUE THREAD

**Issue by kaiwen-wang** [UB-Mannheim/zotero-ocr#55]
Note: the process works fine, it's just that the OCR'd PDF does not link to group libraries so it seems like nothing at all has happened.

It works fine in 'my library.'

Group Library:
<img width="750" alt="image" src="https://github.com/UB-Mannheim/zotero-ocr/assets/33988111/95c9334b-53c4-4899-9f7b-b9a3214a4ac6">
<img width="693" alt="image" src="https://github.com/UB-Mannheim/zotero-ocr/assets/33988111/98810cd5-2a59-4543-aa13-a543d1163045">

My Library:
<img width="747" alt="image" src="https://github.com/UB-Mannheim/zotero-ocr/assets/33988111/53d9e573-f633-4d55-9bba-6df6b075ae83">
<img width="703" alt="image" src="https://github.com/UB-Mannheim/zotero-ocr/assets/33988111/f5d4c20e-ef64-4ca9-9581-43624f986da4">

**Comment by aborel** [comment]
This seems to be related to #78 : in my test the output files have been added as top-level items in my personal library instead of children of the group item.

**Comment by aborel** [comment]
Not actually the same problem after a closer look, but I think both issues can be resolved simultaneously.

**Comment by aborel** [comment]
The switch to regular attachements by default instead of linked files in version 0.8.1 resolves the issue.
