### ISSUE TITLE
couldn't open 'nameToUnicode'

### ISSUE THREAD

**Issue by vivek-gd** [UB-Mannheim/zotero-ocr#58]
couldn't open 'nameToUnicode' ,
I/O Error: Couldn't open 'nameToUnicode' file 'node_modules\node-poppler\src\lib\win32\poppler-22.04.0\share\poppler\nameToUnicode\Bulgarian'
I/O Error: Couldn't open 'nameToUnicode' file 'node_modules\node-poppler\src\lib\win32\poppler-22.04.0\share\poppler\nameToUnicode\Greek'
I/O Error: Couldn't open 'nameToUnicode' file 'node_modules\node-poppler\src\lib\win32\poppler-22.04.0\share\poppler\nameToUnicode\Thai'

**Comment by stweil** [comment]
Try to fix the installation of `pdftoppm`.

**Comment by aborel** [comment]
@vivek-gd Is your problem solved?

**Comment by vivek-gd** [comment]
maybe I've already forgotten.

> @vivek-gd Is your problem solved?

**Comment by aborel** [comment]
Closing.
