### ISSUE TITLE
No bin.exe executable found

### ISSUE THREAD

**Issue by poricaihong** [UB-Mannheim/zotero-ocr#65]
Can not found  bin.exe in pdftoppm.

**Comment by stweil** [comment]
I don't understand you. There is no `bin.exe` required anywhere. Please read the documentation and check your configuration.

**Comment by poricaihong** [comment]
thanks stweil and auphilip. I have reset the file location to "C:\Program Files\poppler-22.04.0\Library\bin" in zotero OCR reference, but an error message box "No C:\Program Files\pdftoppm\Library\bin.exe executable found." came out.

**Comment by stweil** [comment]
That setting is wrong. The plugin does not expect the file location. You have to specify the full name of the executable.

**Comment by poricaihong** [comment]
Yes, Reset the file to executable name. thanks

**Comment by poricaihong** [comment]
Thanks
----- 原始邮件 -----
发件人：Stefan Weil ***@***.***>
收件人：UB-Mannheim/zotero-ocr ***@***.***>
抄送人：poricaihong ***@***.***>,  Author ***@***.***>
主题：Re: [UB-Mannheim/zotero-ocr] No bin.exe executable found (Issue #65)
日期：2024年04月01日 09点54分


That setting is wrong. The plugin does not expect the file location. You have to specify the full name of the executable.

**Comment by poricaihong** [comment]
thanks
----- 原始邮件 -----
发件人：Philipp Zumstein ***@***.***>
收件人：UB-Mannheim/zotero-ocr ***@***.***>
抄送人：poricaihong ***@***.***>,  Author ***@***.***>
主题：Re: [UB-Mannheim/zotero-ocr] No bin.exe executable found (Issue #65)
日期：2024年03月29日 17点01分


For me it sounds as you have entered a Linux path of pdftoppm into the settings. For Windows you need something like this C:\Program Files\poppler-22.04.0\Library\bin\pdftoppm.exe in this field.

**Comment by poricaihong** [comment]
thanks
----- 原始邮件 -----
发件人：Stefan Weil ***@***.***>
收件人：UB-Mannheim/zotero-ocr ***@***.***>
抄送人：poricaihong ***@***.***>,  Author ***@***.***>
主题：Re: [UB-Mannheim/zotero-ocr] No bin.exe executable found (Issue #65)
日期：2024年03月29日 14点59分


I don't understand you. There is no bin.exe required anywhere. Please read the documentation and check your configuration.
