### ISSUE TITLE
Document names with spaces don't work on Windows

### ISSUE THREAD

**Issue by stweil** [UB-Mannheim/zotero-ocr#7]
In a test on Windows, the OCR failed when the name of the PDF includes space characters.

The same test still has to be done for Linux and macOS.

**Comment by pmwills** [comment]
I am having the same problem. 

To add, I can run the relevant commands (after installing poppler) from the command line with success, provided the command and file names are wrapped in the necessary quotes. But what appears to be the same command does not work when run from the extension. 

As far as I can tell, the extension relies on Zotero.Utilities.Internal.exec to handle the Windows-specific side of this, and Zotero.Utilities.Internal.exec in turn relies on nsiProcess. I've been unable to trace it further than that.

**Comment by zuphilip** [comment]
Is this still a problem in the newest version?

It works fine for me on Windows in version 0.4.0 also for PDFs with spaces.

**Comment by serovar** [comment]
Works for me too on Windows 10, thanks

**Comment by stweil** [comment]
Thanks for testing. So I think this issue can be closed.
