### ISSUE TITLE
TypeError: IOUtils.DirectoryIterator is not a constructor

### ISSUE THREAD

**Issue by kai-kea** [UB-Mannheim/zotero-ocr#70]
Error when running on linked or unlinked pdf, with lots of different options. Windows.

```
[JavaScript Error: "TypeError: IOUtils.DirectoryIterator is not a constructor" {file: "jar:file:///C:/Users/kai-kea/AppData/Roaming/Zotero/Zotero/Profiles/oenqx7ul.default/extensions/zotero-ocr@bib.uni-mannheim.de.xpi!/zotero-ocr.js" line: 197}]
````

[git blame](https://github.com/UB-Mannheim/zotero-ocr/blame/master/src/zotero-ocr.js#L197): seems like it slipped into most recent release (last week). Specific case is addressed by Mozilla in [their docs](https://firefox-source-docs.mozilla.org/dom/ioutils_migration.html#iterate-a-directory)

**Comment by stweil** [comment]
Which Zotero version are you running?

**Comment by aborel** [comment]
I am able to reproduce with beta76. The beta70+ compatibility fix was not 100% correct, sorry about that. I had not detected this error because I was testing the plugin on the same PDF over and over again, and the relevant code section was skipped due to an existing `image-list.txt` file. If I delete it, the error happens.

**Comment by aborel** [comment]
No worries, you provided more than enough information for me to locate the source of the problem. Now all I need to do is properly write the relevant 2 or 3 lines code ;-)

**Comment by aborel** [comment]
Version 0.7.2 should solve the problem. The implementation of that particular section in the Zotero7-compatible code was incorrect in 0.7.1, I apologize and hope that we have a satisfying plugin now.

**Comment by stweil** [comment]
@aborel, thank you for fixing this. I added commit 83c1f33b5ccb72900a76c6a7d476fb3f0537ad57 to update the release files and moved the 0.7.2 tag. Now the plugin update works, too.

**Comment by aborel** [comment]
Thanks @stweil I need to be more careful with the release procedure.
