### ISSUE TITLE
Github actions

### ISSUE THREAD

**Issue by denismaier** [UB-Mannheim/zotero-ocr#74]
I'm trying to understand how I can use Github Actions to simplify the development workflow for my own plugin, and I'm trying to learn from your example. Could you perhaps describe your workflow a bit more in detail? What will trigger the workflow to run? I've tried to use a script that pushes a new tag which should work, but this here doesn't work: `(git describe --tags || echo ci-test)`. It seems that `actions/checkout@v4` doesn't fetches the tags.

```sh
#!/bin/bash

################################################
# Get next version number
################################################

current=$(git describe --tags)
echo "Current version: $current"
read -r -p "Enter new version number: " version
echo "Next version set to: $version"

################################################
## Update install.rdf and manifest.json
################################################

perl -pi -e "s/em:version=\"[^\"]*/em:version=\"$version/;" src/install.rdf
# perl -pi -e "s/\"version\": \"[^\"]*\"/\"version\": \"$version\"/" src/manifest.json

################################################
# Commit and push
################################################

git add src/install.rdf #src/manifest.json
git commit -m "Version ${version}" 1>&2
git push
git tag -a -m "Version ${version}" "${version}"
git push origin "${version}"
```

**Comment by zuphilip** [comment]
Our GitHub action is only to test the build process, i.e. if everything works fine it will give the green checkmark for a push or pull request. More details on the specific build and some uploaded artifact can then also been found; here is an example for that: https://github.com/UB-Mannheim/zotero-ocr/actions/runs/8866762703/job/24344584855

Our release process involve still some manual steps locally and adjustements on GitHub's site, cf. https://github.com/UB-Mannheim/zotero-ocr?tab=readme-ov-file#build-and-release . An idea therebyis also, that one wants to first locally test the XPI file in Zotero and only upload it, if everything seems to be okay.

**Comment by denismaier** [comment]
I see. I've now decided to implement an automatic build and release workflow that doesn't rely on tags, but uses the version information in `manifest.json`.
