### ISSUE TITLE
Problem with isolated PDFs with no parent item

### ISSUE THREAD

**Issue by aborel** [UB-Mannheim/zotero-ocr#78]
If the plugin is used on a PDF with no parent item, the output (OCRed PDF, html files) will also be attached to Zotero as isolated files. There will be no visible relation between these scattered items and it will be difficult to find them in a medium or large library.
This risk of such a case is significant as image PDFs might not contain much recognizable metadata recognizable by Zotero at import time.

Maybe it would be good to check for the existence of a parent record, and create one with suitable minimal information if there is none?

**Comment by aborel** [comment]
Commit b61ca1fc96e3359f956f5bf1198387bc1e7c6626 addresses the issue, as well as #55 . Can someone check (and maybe test with Zotero 6 )?

**Comment by stweil** [comment]
As there was no further feedback, I just prepared a new release 0.8.0. So everybody will get the fix, and hopefully some people will report whether it works or not.

**Comment by aborel** [comment]
No problem has been reported in this area, let's close the issue.
