### ISSUE TITLE
Can't open the new OCR PDF with text layer

### ISSUE THREAD

**Issue by wywang1995** [UB-Mannheim/zotero-ocr#83]
Hello,

I have successfully applied the OCR tool to my PDFs and set the "Save output as a PDF with text layer" option in the setting. However, when opening the OCR pdf output file, it was mentioned that the file was damaged. 

Any idea why this is happening and how I can solve it?

Many thanks!

**Comment by aborel** [comment]
I suppose that the plugin exited abnormally, but we would need more details to understand why.
Can you post a screenshot of your Zotero-OCR preferences? 

Is the original PDF a stand-alone PDF, a  regular attachment, or a linked file?
What is the size of the originial and the output PDFs?

**Comment by aborel** [comment]
it would be good to have more details. This sounds like an important bug to fix, but we need more information in order to properly address the issue.

**Comment by aborel** [comment]
@wywang1995 Please tell us more about the problem so that we can address it.

**Comment by aborel** [comment]
Without any further input, I'm closing the issue. Feel free to re-open if someone can provide more details.
