### ISSUE TITLE
Syntax Error (739045): Unknown segment type in JBIG2 stream

### ISSUE THREAD

**Issue by sanjin725** [UB-Mannheim/zotero-ocr#86]
Hello, what is the situation of Syntax Error (739045): Unknown segment type in JBIG2 stream? Did I not set it up properly somewhere?

Syntax Error (598753): Unknown segment type in JBIG2 stream
Syntax Error (609838): Unknown segment type in JBIG2 stream
Syntax Error (616380): Unknown segment type in JBIG2 stream
Syntax Error (633471): Unknown segment type in JBIG2 stream
Syntax Error (642934): Unknown segment type in JBIG2 stream
Syntax Error (671218): Unknown segment type in JBIG2 stream
Syntax Error (712548): Unknown segment type in JBIG2 stream
Syntax Error (739045): Unknown segment type in JBIG2 stream
Syntax Error (788899): Unknown segment type in JBIG2 stream
Syntax Error (822624): Unknown segment type in JBIG2 stream
Syntax Error (880168): Unknown segment type in JBIG2 stream
Syntax Error (904506): Unknown segment type in JBIG2 stream
Syntax Error (948394): Unknown segment type in JBIG2 stream
Syntax Error (988742): Unknown segment type in JBIG2 stream
Syntax Error (1014133): Unknown segment type in JBIG2 stream
Syntax Error (1052872): Unknown segment type in JBIG2 stream
Syntax Error (1089678): Unknown segment type in JBIG2 stream
Syntax Error (1124453): Unknown segment type in JBIG2 stream
Syntax Error (1162440): Unknown segment type in JBIG2 stream
Syntax Error (1198865): Unknown segment type in JBIG2 stream
Syntax Error (1227435): Unknown segment type in JBIG2 stream
Syntax Error (1229843): Unknown segment type in JBIG2 stream
Syntax Error (1231262): Unknown segment type in JBIG2 stream
Syntax Error (1284549): Unknown segment type in JBIG2 stream
Syntax Error (1361009): Unknown segment type in JBIG2 stream
Syntax Error (1406878): Unknown segment type in JBIG2 stream
Syntax Error (1464891): Unknown segment type in JBIG2 stream

**Comment by aborel** [comment]
Your set-up is probably fine, I suspect there is something strange with the file you are trying to OCR. Can you share a link to the file, so that we can take a closer look?

**Comment by aborel** [comment]
My question still stands.

**Comment by aborel** [comment]
We really need to look at the PDF that caused these problems, otherwise I don't know how we can help you.

**Comment by aborel** [comment]
Since there is no further input, I'm closing the issue.
Apparently the error message comes from https://github.com/davidben/poppler/blob/master/poppler/JBIG2Stream.cc (for future reference).
