### ISSUE TITLE
Zotero OCR plugin does nothing.

### ISSUE THREAD

**Issue by JoeJackMedley** [UB-Mannheim/zotero-ocr#87]
I've never, actually, submitted an issue for anything, but I'm at a loss. I thought I'd start out by giving details about my system. Please let me know if you need any other information. This is what I could think of, off the top of my head.

Software Versions:
MacOS: Ventura 13.7.1 (22H221)
Zotero: 7.0.9
tesseract: 5.5.0
poppler: 24.11.0

I have tesseract and poppler installed at the following locations, as confirmed by the commands "brew list tesseract" and "brew list poppler"
/usr/local/Cellar/tesseract/5.4.0/bin/tesseract
/usr/local/Cellar/poppler/24.11.0/bin/pdftoppm

The plugin seems to be installed properly, but when I control+click on the PDF and select "OCR Selected PDF(s)," nothing happens. I get no errors, nothing. I cannot seem to find other instances of this problem.

Any help would be greatly appreciated! Thank you for your time!

**Comment by JoeJackMedley** [comment]
There do seem to be some errors being thrown. When I go to Tools > Developer > Error Console, I get the following that might be helpful to someone else?

18:08:51.977
Style with ID http://www.zotero.org/styles/mary-ann-liebert-harvard already loaded from mary-ann-liebert-harvard.csl [style.js:182](chrome://zotero/content/xpcom/style.js)
18:09:26.421 InstallTrigger is deprecated and will be removed in the future. 2 [reader.js:20136:16](resource://zotero/reader/reader.js)
18:09:26.477 Partitioned cookie or storage access was provided to “resource://zotero/reader/pdf/web/viewer.html” because it is loaded in the third-party context and dynamic state partitioning is enabled.

18:09:26.873 Warning: Bad value, for custom key "AAPL:Keywords", in Info: https://archive.org/details/essais0000unse_p1t2. [pdf.worker.mjs:4893:13](resource://zotero/reader/pdf/build/pdf.worker.mjs)
18:09:26.925 PDF 737ea2e0492cad37520e579aa267bece [1.4 macOS Version 13.7.1 (Build 22H221) Quartz PDFContext, AppendMode 1.1 / Internet Archive (Scribe Version 6.8-initial-140-g3ea0cfc6)] (PDF.js: 4.5.0 [80dd982]) [viewer.mjs:18418:13](resource://zotero/reader/pdf/web/viewer.mjs)
18:09:28.572 NS_ERROR_FILE_UNRECOGNIZED_PATH: Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIFile.initWithPath] [zotero-ocr.js:85](jar:file:///Users/josephmedley/Library/Application%20Support/Zotero/Profiles/2h5j04ke.default/extensions/zotero-ocr@bib.uni-mannheim.de.xpi!/zotero-ocr.js)
18:09:39.929
DOMException: Could not get children of file(/Users/josephmedley/Library/Application Support/Zotero/Crash Reports/events) because it does not exist [CrashManager.sys.mjs:663:17](resource://gre/modules/CrashManager.sys.mjs)

**Comment by aborel** [comment]
The plugin fails at the point where it tries to verify the path to tesseract. Did you set the full paths to tesseract and pdftoppm to your settings? 

Just in case: I would recommend the usual Homebrew symlinks /opt/homebrew/bin/tesseract and /opt/homebrew/bin/pdftoppm (or /usr/local/bin/<program> depending on your system versions) rather than the ones in your Cellar, as the latter will change after version upgrades.

**Comment by JoeJackMedley** [comment]
Is there another way that I can confirm that, other than using the "brew list tesseract" function that I stated I used earlier? Regardless those paths are correct.

**Comment by stweil** [comment]
Try `type tesseract` or `which tesseract`. The `tesseract` executable should be installed as symbolic link in `/usr/local/bin/tesseract`, and your configuration of Zotero OCR should use this full path.

**Comment by stweil** [comment]
> tesseract: 5.5.0
> 
> I have tesseract and poppler installed at the following locations, as confirmed by the commands "brew list tesseract" and "brew list poppler" /usr/local/Cellar/tesseract/5.4.0/bin/tesseract

There is a discrepancy in the version of Tesseract. Is it 5.4.0 or 5.5.0? Try `tesseract --version`, and remove any relics of other versions from `/usr/local/Cellar/tesseract`.

**Comment by aborel** [comment]
It doesn't really matter whether the location of the Homebrew executable symlinks is /opt/homebrew/bin or /usr/local/bin ; what matters is that you have set the appropriate full path in the Zotero-OCR settings. Is it the case? Don't hesitate to post a screenshot of your settings, it can make it easier to see possible problems and to propose precise solutions :-)

**Comment by JoeJackMedley** [comment]
Well, thank you for a conmand that might help figure out where tesseract is.
**_According to the "which" command_**, I found it to be at this location: /usr/local/bin/tesseract

New errors:

**_08:51:13.855 /usr/local/bin/tesseract failed [utilities_internal.js:608](chrome://zotero/content/xpcom/utilities_internal.js)_**
08:51:13.868 Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIFile.copyToFollowingLinks] [file.js:1006](chrome://zotero/content/xpcom/file.js)
08:51:13.868 Failed importing file /Users/josephmedley/Zotero/storage/EGYG4JEK/Des Cannibales.ocr.pdf
08:51:13.872 NS_ERROR_FILE_NOT_FOUND: Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIFile.copyToFollowingLinks] [file.js:1006](chrome://zotero/content/xpcom/file.js)
08:51:16.298 /usr/local/bin/tesseract failed [utilities_internal.js:608](chrome://zotero/content/xpcom/utilities_internal.js)
08:51:16.316 Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIFile.copyToFollowingLinks] [file.js:1006](chrome://zotero/content/xpcom/file.js)
08:51:16.316 Failed importing file /Users/josephmedley/Zotero/storage/EGYG4JEK/Des Cannibales.ocr.pdf
08:51:16.317 NS_ERROR_FILE_NOT_FOUND: Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIFile.copyToFollowingLinks] [file.js:1006](chrome://zotero/content/xpcom/file.js)

**Comment by stweil** [comment]
Does it work for PDF files without a space in the filename? Try a copy of "Des Cannibales.pdf" and name it "Des_Cannibales.pdf".

**Comment by JoeJackMedley** [comment]
So, I reviewed the previous two comments. I'm not sure where the 5.4.0 came from, with respect to the file path. I could have sworn I copied and pasted that path, but I must not have (I can confirm that "4" was a fat-finger though, everything else confirms tesseract version 5.5.0).

I tried the underscore to no avail. New errors confirm that the file has the underscore in it (oddly enough, I had to keep updating it in Zotero before it finally took).

NEW ERRORS:
09:14:24.487 /usr/local/bin/tesseract failed [utilities_internal.js:608](chrome://zotero/content/xpcom/utilities_internal.js)
09:14:24.509 Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIFile.copyToFollowingLinks] [file.js:1006](chrome://zotero/content/xpcom/file.js)
09:14:24.509 Failed importing file /Users/josephmedley/Zotero/storage/EGYG4JEK/Des_Cannibales.ocr.pdf
09:14:24.511 NS_ERROR_FILE_NOT_FOUND: Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIFile.copyToFollowingLinks] [file.js:1006](chrome://zotero/content/xpcom/file.js)

**Comment by JoeJackMedley** [comment]
So, I tested it out on English language material that I needed to pass through OCR, and the same errors occurred. I thought that my Mac's Preview app was able to get OCR on that file to work (spoiler alert: I was wrong, Preview doesn't get it either). I asked Zotero to show me the actual file in my finder, and it looks like Zotero-OCR produced an "image-list.txt" file (attached), as well as a *.png for each page of the original PDF (the images look good, I just thought I wouldn't upload that).

[image-list.txt](https://github.com/user-attachments/files/17921910/image-list.txt)

As for my settings, I have also attached an screenshot.

<img width="792" alt="Screenshot 2024-11-26 at 09 32 08" src="https://github.com/user-attachments/assets/23bf097f-2829-4237-b91b-cd361fe77de4">

Please, let me know what else I can do!

**Comment by aborel** [comment]
The language should be written as a 3-letter code (fre instead of french), see https://tesseract-ocr.github.io/tessdoc/Command-Line-Usage.html

pdftoppm has apparently worked as expected, since all PNG files are present and accounted for.

**Comment by stweil** [comment]
> The language should be written as a 3-letter code (fre instead of french)

... unless the model file has a different name. There are also model files for scripts, for example "Latin". And some languages have variations, for example "deu_latf" for German Fraktur.

**Comment by aborel** [comment]
Oh. OK, understood.

**Comment by stweil** [comment]
For historic French and German texts (early prints until 20th century) I suggest to try our model german_print (the name is misleading). See https://ub-backup.bib.uni-mannheim.de/~stweil/tesstrain/ for this and more models.

**Comment by JoeJackMedley** [comment]
So, I've never dealt with these models before, but I'm not totally incompetent (I'm a former analyst and also work as a scientist while studying Germanistik). Is there maybe an explainer you might suggest, to better understand the link you sent?

I'm curious, when you say, "prints of German (and French?) texts, pre-20th century," are you referring to Fraktur, exclusively, or would german_print be able to recognize something like Schwabacher or other "gothic" (for lack of a better word) typefaces?

**Comment by stweil** [comment]
Maybe [this wiki article](https://github.com/UB-Mannheim/tesstrain/wiki) answers (at least some of) your questions.

**Comment by Calorion** [comment]
>Did you set the full paths to tesseract and pdftoppm to your settings?

Does that mean that this bit in the documentation is not correct?

>By default the fields for the paths to the OCR engine and pdftoppm are empty, which means, that the usual locations are looked at.

**Comment by aborel** [comment]
The documentation is correct, if the paths have not been set manually the plugin will look for a few likely places where the executables could be. But it is entirely possible that someone's system could have them in entirely different locations - so I asked, just in case.

**Comment by bhoconnor** [comment]
Thanks for this you all, helped me get mine working!
