### ISSUE TITLE
Make some output optionally to keep

### ISSUE THREAD

**Issue by zuphilip** [UB-Mannheim/zotero-ocr#9]
Currently all Files that are created during the process are kept. That includes the png-Files, the pdf. For my testfile that results in 35,8 MB for a 274 KB file. Assuming that scaling: If a perform OCR on all files of my 4GB zotero library (which I would want to search for stuff), it will grow to 520 GB. I would suggest to get rid of all the png files and to set an option if the *.ocr.pdf should get created at all (which takes around 15 MB of the 35.8).

_Originally posted by @luerhard in https://github.com/UB-Mannheim/zotero-ocr/pull/6#issuecomment-553954838_

**Comment by zuphilip** [comment]
I'll chime in here too, because I have the same feedback as @luerhard - I'd love to see an option that gets rid of all extraneous stuff (image, hocr, text, etc. files) and keeps only the OCR-ed PDF file. Other than that this is awesome! :)

_Originally posted by @akavalar in https://github.com/UB-Mannheim/zotero-ocr/pull/6#issuecomment-557638891_

**Comment by zuphilip** [comment]
Yeah, currently we tried several things to provide and have some more ideas for the hocr-file see #2. I understand that not all of these might be needed in the end and maybe even different users want to have different output files.

Usually the PDF should only get an additional text layer such that the size should be more or less the same. However, I expect that an increase in the file size might happen, when you have heavily compressed the initial PDF or it uses low-resolution images.

The PNG images are useful if you may want to OCR the same PDF again (maybe with different settings). Because then the same images can be used and you don't have to wait for the first step to complete.

I would suggest that we make the output configurable in the settings. Then we can simply have a line for each output and the user can choose to save this or not, i.e. something like this:
- Output settings
   - [x] Save note of the outputted text
   - [x] Save PDF with additional text layer
      - [ ] Overwrite the additional PDF
   - [x] Save hocr file
   - [x] Save the PNG files for faster re-OCR

What do you think?

**Comment by luerhard** [comment]
That is exactly, what I would be looking for !

**Comment by zuphilip** [comment]
This is now implemented in latest commits.
